### PR TITLE
Add dockerfile for liboqs-go

### PR DESCRIPTION
**Pull request by JannisFengler**
This is a multistage dockerfile which builds liboqs in a build container and then exports the build artifacts to a second container to keep the image as small as possible. After that, it installs liboqs-go and makes it available for Go modules.

### CODE REVIEW

**Review by baentsch — COMMENTED** [review]
Thanks for your contribution! Basically LGTM, but it would be even better with some documentation. One suggestion would be to add the Dockerfile to its own directory that then also includes a README.md with build and/or usage information. See example at https://github.com/open-quantum-safe/liboqs-python/tree/main/docker

**Comment by JannisFengler** [comment]
I made a new sub directory and added a little documentation :)

**Review by baentsch — APPROVED** [review]
Thanks for the update. LGTM. Would you want to see this hosted at docker hub? If so, please add an auto-build-test-and-push component to .circleci/config.yml along the lines of [liboqs-python's docker image](https://github.com/open-quantum-safe/liboqs-python/blob/7e08920a758356bd4530558b8def9ce8bb8e6427/.circleci/config.yml#L83-L117).

**Comment by JannisFengler** [comment]
It would be great if this container is hosted at docker hub. I changed the Dockerfile so that it builds the tests per default instead of the kem example.  As next step, I will add the .circleci file.

**Review by baentsch — APPROVED** [review]
Thanks very much!

**Comment by baentsch** [comment]
@JannisFengler The image is now accessible at https://hub.docker.com/repository/docker/openquantumsafe/go. Would you agree that now an update (simplification) to https://github.com/open-quantum-safe/liboqs-go#quick-and-dirty-execution-of-examples-with-disposable-docker-containers is sensible? If so, would you want to do another PR for that in the README (and possibly add yourself as a contributor there) or shall we add some suitable language?

**Comment by JannisFengler** [comment]
I will update the readme in another PR. Maybe it also makes sense to update the use of the docker container so it mounts the directory of the user.

**Comment by baentsch** [comment]
> Maybe it also makes sense to update the use of the docker container so it mounts the directory of the user.

Quite possibly. My approach for the docker README is to consider people _only_ reading the [documentation at docker hub](https://hub.docker.com/repository/docker/openquantumsafe/go) and not being versed in PQC. That then gives me contents for a self-contained README that is simply copied as-is to docker-hub. For now I put links at docker hub as I (currently) think that both, docker and project, READMEs are required to understand the contents of the docker image.

**Pull request merged**
